"""Local deployment: merged HF model → GGUF → Ollama.

Workflow (after you've trained on Kaggle and downloaded the `merged_hf/`
directory the notebook produced):

    python deploy/convert_and_deploy.py `
      --merged ./merged_hf `
      --name aidflow-camp `
      --tag e4b-lora-v01 `
      --quant Q4_K_M

What this does:
  1. Clones llama.cpp into ./deploy/.llamacpp/ if not already present
     (single-file Python conversion scripts — no C++ build required).
  2. Runs `convert_hf_to_gguf.py` to produce <name>-<tag>.gguf in the
     chosen quantization (default Q4_K_M, ~3-4 GB for 4B class models).
  3. Writes a Modelfile and runs `ollama create <name>:<tag>`.
  4. Prints the model name you can drop into src/services/ollama.ts.

Prerequisites:
  - Python 3.10+ on PATH (only stdlib + a couple of pip packages used here)
  - git on PATH (for cloning llama.cpp)
  - ollama on PATH (https://ollama.com/download)
  - llama.cpp's convert script has its own pip deps; we pip-install them
    into the active environment on first run.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

LLAMACPP_REPO = "https://github.com/ggerganov/llama.cpp.git"
DEFAULT_LLAMACPP_DIR = Path(__file__).resolve().parent / ".llamacpp"
# Convert-script deps. Keep this list narrow; llama.cpp's requirements.txt
# is large and overlaps with packages most users already have.
CONVERT_DEPS = [
    "numpy",
    "torch",
    "transformers>=4.45",
    "sentencepiece",
    "protobuf",
    "safetensors",
    "gguf",
]


def run(cmd: list[str], cwd: Path | None = None, check: bool = True) -> None:
    """Run a subprocess, streaming output to our stdout."""
    printable = " ".join(str(c) for c in cmd)
    print(f"\n$ {printable}\n", flush=True)
    result = subprocess.run(cmd, cwd=str(cwd) if cwd else None)
    if check and result.returncode != 0:
        print(f"!! command failed (exit {result.returncode}): {printable}", file=sys.stderr)
        sys.exit(result.returncode)


def ensure_llamacpp(llamacpp_dir: Path) -> Path:
    """Clone llama.cpp into `llamacpp_dir` if it's not there. Return its path."""
    if (llamacpp_dir / "convert_hf_to_gguf.py").exists():
        print(f"-- llama.cpp already present at {llamacpp_dir}")
        return llamacpp_dir
    llamacpp_dir.parent.mkdir(parents=True, exist_ok=True)
    print(f"-- cloning llama.cpp into {llamacpp_dir} (shallow)...")
    run(["git", "clone", "--depth", "1", LLAMACPP_REPO, str(llamacpp_dir)])
    if not (llamacpp_dir / "convert_hf_to_gguf.py").exists():
        print(
            "!! llama.cpp clone succeeded but convert_hf_to_gguf.py is missing. "
            "The script may have been renamed upstream — check llama.cpp/ for the "
            "current conversion entry point and edit this file.",
            file=sys.stderr,
        )
        sys.exit(1)
    return llamacpp_dir


def ensure_convert_deps() -> None:
    """Pip-install just the packages convert_hf_to_gguf.py imports."""
    print(f"-- installing convert-script Python deps: {CONVERT_DEPS}")
    run([sys.executable, "-m", "pip", "install", "--quiet", *CONVERT_DEPS])


def convert_to_gguf(
    llamacpp_dir: Path,
    merged_dir: Path,
    out_gguf: Path,
    quant: str,
) -> None:
    """Invoke llama.cpp's HF→GGUF converter."""
    convert_py = llamacpp_dir / "convert_hf_to_gguf.py"
    run(
        [
            sys.executable,
            str(convert_py),
            str(merged_dir),
            "--outfile",
            str(out_gguf),
            "--outtype",
            quant.lower() if quant.startswith("F") or quant == "BF16" else "auto",
        ],
        cwd=llamacpp_dir,
    )
    if not out_gguf.exists():
        print(f"!! conversion produced no file at {out_gguf}", file=sys.stderr)
        sys.exit(1)
    print(f"-- GGUF written: {out_gguf}  ({out_gguf.stat().st_size / 1024 / 1024:.0f} MB)")
    # NOTE: convert_hf_to_gguf.py emits an unquantized model by default.
    # If you want a smaller, quantized variant (Q4_K_M, Q5_K_M, etc.),
    # you'd run llama.cpp's `quantize` binary against this file. We skip
    # that step here because Ollama can ingest the unquantized GGUF
    # directly and re-quantize internally if needed.


def write_modelfile(gguf_path: Path, modelfile_path: Path, name: str, tag: str) -> None:
    """Write the Ollama Modelfile pointing at our GGUF."""
    content = f"""# AidFlow Pro — fine-tuned Drone Camp Planner model
# Generated by training/deploy/convert_and_deploy.py
# Source: Phase 1 LoRA merge over a Gemma vision base.
FROM {gguf_path.as_posix()}

PARAMETER temperature 0
PARAMETER num_predict 4096

SYSTEM \"\"\"You are a humanitarian field analyst reviewing a top-down aerial image of a displaced-persons settlement, refugee camp, or temporary shelter site.

Identify visible features. Return STRICT JSON with this schema:
{{
  "features": [
    {{"type": "tent", "x": 0..1, "y": 0..1, "confidence": "high"|"medium"|"low"}}
  ],
  "notes": ["short observation 1", "short observation 2"]
}}

COORDINATE SYSTEM: (0,0) is the TOP-LEFT corner. x grows right, y grows down. Use 4-decimal floats.
RULES: Each tent is ONE entry. NEVER invent features. NEVER duplicate. Cap tents at 200. Output ONLY the JSON.\"\"\"
"""
    modelfile_path.write_text(content, encoding="utf-8")
    print(f"-- Modelfile written: {modelfile_path}")


def ollama_create(name: str, tag: str, modelfile_path: Path) -> None:
    """Run `ollama create`."""
    run(["ollama", "create", f"{name}:{tag}", "-f", str(modelfile_path)])


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Convert a merged HF model to GGUF and register it with Ollama."
    )
    ap.add_argument(
        "--merged",
        type=Path,
        required=True,
        help="Path to the merged_hf/ directory downloaded from Kaggle.",
    )
    ap.add_argument("--name", default="aidflow-camp", help="Ollama model name.")
    ap.add_argument("--tag", default="e4b-lora-v01", help="Ollama tag.")
    ap.add_argument(
        "--quant",
        default="auto",
        help="Output dtype for HF→GGUF conversion. 'auto', 'f16', 'bf16', or 'f32'. "
        "Further quantization (Q4_K_M etc.) requires llama.cpp's quantize binary "
        "and is left as a manual step.",
    )
    ap.add_argument(
        "--llamacpp-dir",
        type=Path,
        default=DEFAULT_LLAMACPP_DIR,
        help="Where to clone llama.cpp (default: deploy/.llamacpp/).",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=Path(__file__).resolve().parent / "out",
        help="Where to write the GGUF + Modelfile.",
    )
    ap.add_argument(
        "--skip-deps",
        action="store_true",
        help="Skip the pip-install step for convert-script dependencies.",
    )
    ap.add_argument(
        "--skip-ollama-create",
        action="store_true",
        help="Stop after writing the Modelfile; don't run `ollama create`.",
    )
    args = ap.parse_args()

    merged: Path = args.merged.resolve()
    if not (merged / "config.json").exists():
        print(f"!! {merged} doesn't look like a HF model directory "
              f"(no config.json). Did the Kaggle merge cell run?",
              file=sys.stderr)
        sys.exit(1)

    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    gguf_path = out_dir / f"{args.name}-{args.tag}.gguf"
    modelfile_path = out_dir / f"Modelfile.{args.tag}"

    print(f"== AidFlow Pro deploy")
    print(f"   merged HF dir: {merged}")
    print(f"   output GGUF:   {gguf_path}")
    print(f"   model name:    {args.name}:{args.tag}")

    llamacpp_dir = ensure_llamacpp(args.llamacpp_dir)
    if not args.skip_deps:
        ensure_convert_deps()
    convert_to_gguf(llamacpp_dir, merged, gguf_path, args.quant)
    write_modelfile(gguf_path, modelfile_path, args.name, args.tag)

    if args.skip_ollama_create:
        print("\n-- skipping `ollama create` per --skip-ollama-create.")
        print(f"   to register manually: ollama create {args.name}:{args.tag} -f {modelfile_path}")
        return

    if shutil.which("ollama") is None:
        print("\n!! `ollama` binary not on PATH — install from https://ollama.com/download "
              "then run: ollama create {n}:{t} -f {m}".format(
                  n=args.name, t=args.tag, m=modelfile_path),
              file=sys.stderr)
        sys.exit(1)
    ollama_create(args.name, args.tag, modelfile_path)

    print()
    print(f"== done!")
    print(f"   try:  ollama run {args.name}:{args.tag}  (then drop an aerial image into it)")
    print(f"   or:   python eval/compare.py --base gemma4:e4b --lora {args.name}:{args.tag}")
    print()
    print(f"   To wire AidFlow Pro to use the fine-tuned model, change the model name in")
    print(f"   src/services/ollama.ts from 'gemma4:e4b' to '{args.name}:{args.tag}'.")


if __name__ == "__main__":
    main()
